# Generated by Django 5.2.15 on 2026-06-16 12:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("asset_code", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=200)),
                (
                    "asset_type",
                    models.CharField(
                        choices=[
                            ("current", "Current Asset"),
                            ("fixed", "Fixed Asset"),
                            ("intangible", "Intangible Asset"),
                            ("investment", "Investment"),
                        ],
                        max_length=20,
                    ),
                ),
                ("purchase_date", models.DateField()),
                ("purchase_price", models.IntegerField(default=0)),
                ("current_value", models.IntegerField(default=0)),
                ("depreciation_rate", models.IntegerField(default=0)),
                ("accumulated_depreciation", models.IntegerField(default=0)),
                ("location", models.CharField(blank=True, max_length=200)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("phone", models.CharField(max_length=15)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("address", models.TextField(blank=True)),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        help_text="Primary location/area for deliveries",
                        max_length=200,
                    ),
                ),
                (
                    "apartment_name",
                    models.CharField(
                        blank=True,
                        help_text="Apartment or building name",
                        max_length=200,
                    ),
                ),
                (
                    "floor",
                    models.CharField(
                        blank=True, help_text="Floor number", max_length=50
                    ),
                ),
                (
                    "door_number",
                    models.CharField(
                        blank=True, help_text="Door/apartment number", max_length=50
                    ),
                ),
                ("total_orders", models.IntegerField(default=0)),
                ("total_spent", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Equity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("equity_code", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=200)),
                (
                    "equity_type",
                    models.CharField(
                        choices=[
                            ("capital", "Capital"),
                            ("drawings", "Drawings"),
                            ("reserves", "Reserves"),
                            ("retained_earnings", "Retained Earnings"),
                        ],
                        max_length=20,
                    ),
                ),
                ("amount", models.IntegerField(default=0)),
                ("owner", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="LedgerAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("account_code", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "account_type",
                    models.CharField(
                        choices=[
                            ("asset", "Asset"),
                            ("liability", "Liability"),
                            ("equity", "Equity"),
                            ("revenue", "Revenue"),
                            ("expense", "Expense"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "normal_balance",
                    models.CharField(
                        choices=[("D", "Debit"), ("C", "Credit")], max_length=1
                    ),
                ),
                ("opening_balance", models.IntegerField(default=0)),
                ("current_balance", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Liability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("liability_code", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=200)),
                (
                    "liability_type",
                    models.CharField(
                        choices=[
                            ("current", "Current Liability"),
                            ("long_term", "Long Term Liability"),
                            ("contingent", "Contingent Liability"),
                        ],
                        max_length=20,
                    ),
                ),
                ("amount", models.IntegerField(default=0)),
                ("interest_rate", models.IntegerField(default=0)),
                ("due_date", models.DateField()),
                ("creditor", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=200)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("detergent", "Detergent"),
                            ("water", "Water"),
                            ("electricity", "Electricity"),
                            ("maintenance", "Maintenance"),
                            ("salary", "Salary"),
                            ("rent", "Rent"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "amount",
                    models.IntegerField(
                        default=0, help_text="Amount in KSh (whole numbers only)"
                    ),
                ),
                ("date", models.DateField(auto_now_add=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Journal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("entry_number", models.CharField(max_length=20, unique=True)),
                (
                    "journal_type",
                    models.CharField(
                        choices=[
                            ("general", "General Journal"),
                            ("sales", "Sales Journal"),
                            ("purchases", "Purchases Journal"),
                            ("cash_receipts", "Cash Receipts Journal"),
                            ("cash_payments", "Cash Payments Journal"),
                            ("returns_inwards", "Returns Inwards Journal"),
                            ("returns_outwards", "Returns Outwards Journal"),
                            ("petty_cash", "Petty Cash Journal"),
                        ],
                        max_length=20,
                    ),
                ),
                ("date", models.DateField(auto_now_add=True)),
                ("description", models.TextField()),
                ("reference", models.CharField(blank=True, max_length=50)),
                ("total_amount", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_number",
                    models.CharField(blank=True, max_length=20, unique=True),
                ),
                (
                    "items_description",
                    models.TextField(
                        blank=True, help_text="e.g., 5 bedsheets, 3 jackets, 2 jeans"
                    ),
                ),
                (
                    "weight_kg",
                    models.IntegerField(
                        default=0, help_text="Weight in kilograms (whole numbers only)"
                    ),
                ),
                (
                    "price_per_kg",
                    models.IntegerField(
                        default=100, help_text="Price per kilogram in KSh"
                    ),
                ),
                (
                    "total_amount",
                    models.IntegerField(default=0, help_text="Total amount in KSh"),
                ),
                (
                    "paid_amount",
                    models.IntegerField(default=0, help_text="Amount paid in KSh"),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("unpaid", "Unpaid"),
                            ("partial", "Partially Paid"),
                            ("paid", "Paid"),
                        ],
                        default="unpaid",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("received", "Received"),
                            ("washing", "Washing"),
                            ("drying", "Drying"),
                            ("folding", "Folding"),
                            ("ready", "Ready for Pickup"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="received",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "pickup_date",
                    models.DateField(
                        blank=True,
                        help_text="Date when customer will pick up",
                        null=True,
                    ),
                ),
                (
                    "collection_date",
                    models.DateField(
                        blank=True,
                        help_text="Date when clothes are ready for collection",
                        null=True,
                    ),
                ),
                ("sms_sent", models.BooleanField(default=False)),
                ("sms_order_received_sent", models.BooleanField(default=False)),
                ("sms_ready_sent", models.BooleanField(default=False)),
                ("sms_payment_sent", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to="laundry.customer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="JournalEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("debit", models.IntegerField(default=0)),
                ("credit", models.IntegerField(default=0)),
                ("description", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "expense",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="laundry.expense",
                    ),
                ),
                (
                    "journal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="laundry.journal",
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="laundry.ledgeraccount",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="laundry.order",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True)),
                ("description", models.TextField()),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("purchase", "Purchase"),
                            ("sale", "Sale"),
                            ("expense", "Expense"),
                            ("payment", "Payment"),
                            ("receipt", "Receipt"),
                            ("transfer", "Transfer"),
                            ("adjustment", "Adjustment"),
                        ],
                        max_length=20,
                    ),
                ),
                ("amount", models.IntegerField(default=0)),
                (
                    "detected_category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("asset", "Asset"),
                            ("liability", "Liability"),
                            ("equity", "Equity"),
                            ("revenue", "Revenue"),
                            ("expense", "Expense"),
                            ("contra_asset", "Contra Asset"),
                            ("contra_liability", "Contra Liability"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("confidence_score", models.IntegerField(default=0)),
                ("reference_number", models.CharField(blank=True, max_length=50)),
                ("verified", models.BooleanField(default=False)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "detected_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="laundry.ledgeraccount",
                    ),
                ),
                (
                    "related_asset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="laundry.asset",
                    ),
                ),
                (
                    "related_expense",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="laundry.expense",
                    ),
                ),
                (
                    "related_journal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="laundry.journal",
                    ),
                ),
                (
                    "related_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="laundry.order",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
