# Generated by Django 5.2.15 on 2026-06-16 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("laundry", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="apartment_name",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="customer",
            name="door_number",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="customer",
            name="floor",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="customer",
            name="location",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="expense",
            name="amount",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="expense",
            name="category",
            field=models.CharField(
                choices=[
                    ("detergent", "Detergent"),
                    ("water", "Water"),
                    ("electricity", "Electricity"),
                    ("maintenance", "Maintenance"),
                    ("salary", "Salary"),
                    ("rent", "Rent"),
                    ("asset_purchase", "Asset Purchase"),
                    ("other", "Other"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="collection_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="items_description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="paid_amount",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="order",
            name="pickup_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="price_per_kg",
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name="order",
            name="total_amount",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="order",
            name="weight_kg",
            field=models.IntegerField(default=0),
        ),
    ]
