# Generated by Django 5.2.15 on 2026-06-14 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("laundry", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="location",
            field=models.CharField(
                blank=True,
                help_text="Primary location/area for deliveries",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="items_description",
            field=models.TextField(
                blank=True, help_text="e.g., 5 bedsheets, 3 jackets, 2 jeans"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="sms_sent",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="order",
            name="price_per_kg",
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("received", "Received"),
                    ("washing", "Washing"),
                    ("drying", "Drying"),
                    ("folding", "Folding"),
                    ("ready", "Ready for Pickup"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                ],
                default="received",
                max_length=20,
            ),
        ),
    ]
