# Generated by Django 5.2.15 on 2026-06-18 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("laundry", "0002_alter_customer_apartment_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="asset",
            name="accumulated_depreciation",
        ),
        migrations.RemoveField(
            model_name="asset",
            name="depreciation_rate",
        ),
    ]
