# Generated by Django 5.2.15 on 2026-06-14 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("laundry", "0002_customer_location_order_items_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_number",
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="total_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
