# Generated by Django 5.2.15 on 2026-06-14 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("laundry", "0003_alter_order_order_number_alter_order_total_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="collection_date",
            field=models.DateField(
                blank=True,
                help_text="Date when clothes are ready for collection",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="pickup_date",
            field=models.DateField(
                blank=True, help_text="Date when customer will pick up", null=True
            ),
        ),
    ]
