# Generated by Django 5.2.15 on 2026-06-19 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("laundry", "0004_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="accumulated_depreciation",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="asset",
            name="depreciation_rate",
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
