# Generated by Django 5.2.15 on 2026-06-19 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("laundry", "0006_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="registration_code",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
