# Generated by Django 5.2.15 on 2026-06-29 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("laundry", "0008_alter_journal_options_alter_journalentry_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="analyzed_data",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
