# Generated by Django 5.2.15 on 2026-06-29 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("laundry", "0009_transaction_analyzed_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="journal",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="laundry.journal",
            ),
        ),
    ]
